"""add storage_objects table and message attachment_url

Revision ID: 20260310_storage
Revises: 64018941537a_merge_timestamp_branch
Create Date: 2026-03-10 00:00:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260310_storage"
down_revision: Union[str, Sequence[str], None] = "64018941537a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_objects",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("bucket", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index(
        op.f("ix_storage_objects_bucket"), "storage_objects", ["bucket"], unique=False
    )

    op.add_column(
        "messages", sa.Column("attachment_url", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "attachment_url")
    op.drop_index(op.f("ix_storage_objects_bucket"), table_name="storage_objects")
    op.drop_table("storage_objects")
    # ### end Alembic commands ###
