from datetime import datetime

from fastapi_users_db_sqlalchemy import SQLAlchemyBaseUserTable
from sqlalchemy import Boolean, Column, DateTime, Integer, String
from sqlalchemy.orm import relationship

from ..base import Base


class User(SQLAlchemyBaseUserTable[int], Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)

    # These are required by SQLAlchemyBaseUserTable but ensure they're properly defined
    email = Column(String(254), unique=True, nullable=False)
    # `username` must be supplied by the application (or generated by the
    # user manager).  We no longer provide a Python-level default of an empty
    # string, because that led to duplicate-key errors when multiple users
    # were created without specifying a username.  The column is still
    # non‑nullable and unique at the database level.
    username = Column(String(255), unique=True, nullable=False)
    hashed_password = Column(String(1024), nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    is_superuser = Column(Boolean, default=False, nullable=False)
    is_verified = Column(Boolean, default=False, nullable=False)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    chats = relationship("Chat", back_populates="owner")
